importing libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

importing dataset

In [2]:
tracker_set = pd.read_excel("Documents/Transportation & Logistics Tracking Dataset.xlsx")

view dataset

In [3]:
tracker_set

,Gps Provider,Booking ID,Shipment Type,Booking Date,Vehicle Registration,Origin Location,Destination Location,Origin Location Latitude,Origin Location Longitude,Destination Location Latitude,...,Trip Start Date,Trip End Date,Transportation Distance (KM),Vehicle Type,Minimum Kms To Be Covered In A Day,Driver Name,Driver Mobile No,Customer Name,Supplier Name,Material Shipped
0,Consent Track,AEIBK2027469,Regular,2020-08-26 12:03:46.000,MH14GD9464,"Shive, Pune, Maharashtra","Pondur, Kanchipuram, Tamil Nadu",18.750621,73.877190,12.930429,...,2020-08-26 16:16:00,2020-08-28 12:15:10,1290.0,32 FT Multi-Axle 14MT - HCV,NaN,VIRAT NILAPALLE,9.960008e+09,Daimler India Commercial Vehicles Pvt Lt,Oms Logistics Pvt Ltd,Regulator - 12v
1,Vamosys,VCV00014153/082021,Regular,2020-08-27 15:21:48.570,TN30BC9320,"Daimler India Commercial Vehicles,Kanchipuram,...","Daimler India Commercial Vehicles,Kanchipuram,...",12.839000,79.954000,12.839000,...,2020-08-27 15:21:06,2020-08-27 15:21:54.947000,29.0,NaN,NaN,SENTHIL KUMAR,NaN,Daimler India Commercial Vehicles Pvt Lt,Vj Logistics,Valve Spring
2,Vamosys,VCV00014063/082021,Regular,2020-08-27 14:22:17.833,TN30BB1036,"Daimler India Commercial Vehicles,Kanchipuram,...","Daimler India Commercial Vehicles,Kanchipuram,...",12.839000,79.954000,12.839000,...,2020-08-27 14:21:21,2020-08-27 14:22:25.037000,21.0,NaN,NaN,ANBU,NaN,Daimler India Commercial Vehicles Pvt Lt,Vj Logistics,Valve Spring
3,Vamosys,VCV00014741/082021,Regular,2020-08-28 00:32:20.523,TN88D4134,"Daimler India Commercial Vehicles,Kanchipuram,...","Daimler India Commercial Vehicles,Kanchipuram,...",12.839000,79.954000,12.839000,...,2020-08-28 00:31:41,2020-08-28 00:32:24.213000,20.0,NaN,NaN,SUDHAKAR,NaN,Daimler India Commercial Vehicles Pvt Lt,Namakkal Sri Anjinaya Transport,Lu Hood Lock / Rh
4,Consent Track,AEIBK2027446,Regular,2020-08-26 09:55:08.000,GJ01DZ8943,"Khorajnanoda, Ahmedabad, Gujarat","Singaperumalkoil, Kanchipuram, Tamil Nadu",22.961777,72.094219,12.786517,...,2020-08-26 15:35:00,2020-08-28 11:21:00,1900.0,32 FT Single-Axle 7MT - HCV,NaN,MAN SINGH,6.396821e+09,Ford India Private Limited,Sterling Translogistics Private Limited,Lu Latch / Pin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3580,Consent Track,AEIBK1909187,Regular,2019-12-20 14:54:06.000,HR38S1605,"Okhla industrial estate, south delhi, delhi","Palam Airport, South West Delhi, Delhi",28.542809,77.280521,28.553908,...,2019-12-20 14:54:06,2020-01-16 15:57:00,25.0,40 FT 3XL Trailer 35MT,250.0,NaN,NaN,Larsen & Toubro Limited,S.B.Transport Company,Yoke & Pole Assembly
3581,Consent Track,AEIBK1907026,Regular,2019-11-29 21:14:49.000,NL01G0589,"Kuldanga, howrah, west bengal","Kuldanga, Howrah, West Bengal",16.560192,80.792293,22.593221,...,2019-11-29 21:14:49,2020-02-05 16:57:55,30.0,40 FT Flat Bed Double-Axle 21MT - Trailer,250.0,NaN,NaN,Larsen & Toubro Limited,Sunita Carriers Private Limited,Rectifier Assembly
3582,Consent Track,AEIBK1906955,Regular,2019-11-30 15:10:27.000,GJ15UU7437,"Changodar, ahmedabad, gujarat","Zanu, Ahmedabad, Gujarat",16.560192,80.792293,23.042185,...,2019-11-30 15:10:27,2020-01-02 14:24:00,25.0,40 FT 3XL Trailer 35MT,250.0,MAHENDRA SINGH,8.949298e+09,Larsen & Toubro Limited,Balaji Freight Carrier,Grs Starter
3583,Null,WDSBKTP49392,Regular,2019-06-10 13:17:44.000,WB59B9152,"Sonai, kolkata, west bengal","Kalyani, Nadia, West Bengal",23.525268,87.264424,22.952176,...,1899-12-30 00:00:00.000,1899-12-30 08:13:00.000,51.0,40 FT Flat Bed Multi-Axle 27MT - Trailer,NaN,NaN,NaN,Larsen & Toubro Limited,Sunita Carriers Private Limited,Fxuwb-Lid Cover
3584,Jtech,WDSBKTP44502,Regular,2019-04-15 15:15:13.000,KA21A5090,"Mugabala, bangalore rural, karnataka","Peenya Small Industries, Bangalore, Karnataka",16.560192,80.792293,13.196313,...,1899-12-30 00:00:00.000,1899-12-30 03:21:00.000,41.0,40 FT 3XL Trailer 35MT,NaN,NaN,NaN,Larsen & Toubro Limited,A S Transports,Insrt-Vlv St Intk

choosing the columns we need for this project, having studied the dataset in excel

In [4]:
tracker_sets = tracker_set[["Gps Provider", "Shipment Type", "Booking Date", "Ontime","Transportation Distance (KM)", "Vehicle Type", "Driver Name", "Supplier Name",
"Material Shipped"]]

counting the null values per variable

In [5]:
for column in tracker_sets.columns.to_list():
    nullval = tracker_sets[column].isnull().value_counts()
    print(nullval)

Gps Provider
False    3585
Name: count, dtype: int64
Shipment Type
False    3585
Name: count, dtype: int64
Booking Date
False    3585
Name: count, dtype: int64
Ontime
False    3585
Name: count, dtype: int64
Transportation Distance (KM)
False    3437
True      148
Name: count, dtype: int64
Vehicle Type
False    2821
True      764
Name: count, dtype: int64
Driver Name
False    3268
True      317
Name: count, dtype: int64
Supplier Name
False    3585
Name: count, dtype: int64
Material Shipped
False    3585
Name: count, dtype: int64

dropping the null values totally

In [6]:
tracker_sets.dropna(subset = ["Transportation Distance (KM)", "Vehicle Type", "Driver Name"], inplace = True)

C:\Users\Hp 830 g5 ci5\AppData\Local\Temp\ipykernel_17400\820053933.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracker_sets.dropna(subset = ["Transportation Distance (KM)", "Vehicle Type", "Driver Name"], inplace = True)

checking our new dataset

In [7]:
for column in tracker_sets.columns.to_list():
    nullval = tracker_sets[column].isnull().value_counts()
    print(nullval)

Gps Provider
False    2414
Name: count, dtype: int64
Shipment Type
False    2414
Name: count, dtype: int64
Booking Date
False    2414
Name: count, dtype: int64
Ontime
False    2414
Name: count, dtype: int64
Transportation Distance (KM)
False    2414
Name: count, dtype: int64
Vehicle Type
False    2414
Name: count, dtype: int64
Driver Name
False    2414
Name: count, dtype: int64
Supplier Name
False    2414
Name: count, dtype: int64
Material Shipped
False    2414
Name: count, dtype: int64

In [8]:
tracker_sets.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2414 entries, 0 to 3582
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Gps Provider                  2414 non-null   object
 1   Shipment Type                 2414 non-null   object
 2   Booking Date                  2414 non-null   datetime64[ns]
 3   Ontime                        2414 non-null   object
 4   Transportation Distance (KM)  2414 non-null   float64
 5   Vehicle Type                  2414 non-null   object
 6   Driver Name                   2414 non-null   object
 7   Supplier Name                 2414 non-null   object
 8   Material Shipped              2414 non-null   object
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 188.6+ KB

extracting month, day and hour from booking date

In [9]:
tracker_sets["Booking Date"]

0      2020-08-26 12:03:46
4      2020-08-26 09:55:08
5      2020-08-25 15:45:33
9      2020-08-25 13:39:48
10     2020-08-25 12:03:57
               ...
3463   2019-12-30 18:23:49
3465   2020-01-07 14:56:40
3530   2019-12-26 19:56:20
3546   2019-12-21 18:48:49
3582   2019-11-30 15:10:27
Name: Booking Date, Length: 2414, dtype: datetime64[ns]

In [10]:
tracker_sets["Month"] = tracker_sets["Booking Date"].dt.month_name()
tracker_sets["Day"] = tracker_sets["Booking Date"].dt.day_name()
tracker_sets["Hour"] = tracker_sets["Booking Date"].dt.hour

C:\Users\Hp 830 g5 ci5\AppData\Local\Temp\ipykernel_17400\2686686907.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracker_sets["Month"] = tracker_sets["Booking Date"].dt.month_name()
C:\Users\Hp 830 g5 ci5\AppData\Local\Temp\ipykernel_17400\2686686907.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracker_sets["Day"] = tracker_sets["Booking Date"].dt.day_name()
C:\Users\Hp 830 g5 ci5\AppData\Local\Temp\ipykernel_17400\2686686907.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracker_sets["Hour"] = tracker_sets["Booking Date"].dt.hour

In [11]:
tracker_sets

,Gps Provider,Shipment Type,Booking Date,Ontime,Transportation Distance (KM),Vehicle Type,Driver Name,Supplier Name,Material Shipped,Month,Day,Hour
0,Consent Track,Regular,2020-08-26 12:03:46,Yes,1290.0,32 FT Multi-Axle 14MT - HCV,VIRAT NILAPALLE,Oms Logistics Pvt Ltd,Regulator - 12v,August,Wednesday,12
4,Consent Track,Regular,2020-08-26 09:55:08,Yes,1900.0,32 FT Single-Axle 7MT - HCV,MAN SINGH,Sterling Translogistics Private Limited,Lu Latch / Pin,August,Wednesday,9
5,Consent Track,Regular,2020-08-25 15:45:33,Yes,400.0,19 FT OPEN BODY 8 MT,BHARATHIDASAN,Gayathri Transport,Planetary Axle,August,Tuesday,15
9,Vamosys,Regular,2020-08-25 13:39:48,Yes,1199.0,32 FT Multi-Axle 14MT - HCV,GOPALAKRISHNAN M,Arvinth Transport,Mounting Bracket / Round Bar,August,Tuesday,13
10,Nuevastech,Regular,2020-08-25 12:03:57,Yes,1290.0,32 FT Multi-Axle 14MT - HCV,RAMCHANDRA,Pratiksha Freight Carriers,Centering Bolt,August,Tuesday,12
...,...,...,...,...,...,...,...,...,...,...,...,...
3463,Consent Track,Regular,2019-12-30 18:23:49,No,78.5,40 FT 3XL Trailer 35MT,BILAL ALI,Unknown,Solenoid Switch,December,Monday,18
3465,Consent Track,Regular,2020-01-07 14:56:40,No,117.0,40 FT 3XL Trailer 35MT,BHARATH HANOKU,United Freight Carriers Private Limited,Solenoid Switch,January,Tuesday,14
3530,Consent Track,Regular,2019-12-26 19:56:20,No,98.1,40 FT Flat Bed Multi-Axle 27MT - Trailer,SHIV LAL MARANDI,Shri Ganesh Traders And Transporter,Plug Modg,December,Thursday,19
3546,Consent Track,Regular,2019-12-21 18:48:49,No,148.0,40 FT 3XL Trailer 35MT,SUNIL RAJWAR,Shri Ganesh Traders And Transporter,Auto Parts,December,Saturday,18
3582,Consent Track,Regular,2019-11-30 15:10:27,No,25.0,40 FT 3XL Trailer 35MT,MAHENDRA SINGH,Balaji Freight Carrier,Grs Starter,November,Saturday,15

Creating a column where we split the Hour variable into morning, day and evening, and the Day variable into weekday and weekend.

In [12]:
hoursplit = np.linspace(tracker_sets["Hour"].min(), tracker_sets["Hour"].max(), num = 4, endpoint = True)
hours = ["morning", "day", "evening"]
tracker_sets["Hours"] = pd.cut(tracker_sets["Hour"], bins = hoursplit, labels = hours, include_lowest = True)

C:\Users\Hp 830 g5 ci5\AppData\Local\Temp\ipykernel_17400\2683524218.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracker_sets["Hours"] = pd.cut(tracker_sets["Hour"], bins = hoursplit, labels = hours, include_lowest = True)

In [13]:
Days = []
for day in tracker_sets["Day"]:
    if day in ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"):
        Days.append("weekday")
    else:
        Days.append("weekend")
tracker_sets["Days"] = Days

C:\Users\Hp 830 g5 ci5\AppData\Local\Temp\ipykernel_17400\2762070472.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracker_sets["Days"] = Days

In [14]:
tracker_sets.head()

,Gps Provider,Shipment Type,Booking Date,Ontime,Transportation Distance (KM),Vehicle Type,Driver Name,Supplier Name,Material Shipped,Month,Day,Hour,Hours,Days
0,Consent Track,Regular,2020-08-26 12:03:46,Yes,1290.0,32 FT Multi-Axle 14MT - HCV,VIRAT NILAPALLE,Oms Logistics Pvt Ltd,Regulator - 12v,August,Wednesday,12,day,weekday
4,Consent Track,Regular,2020-08-26 09:55:08,Yes,1900.0,32 FT Single-Axle 7MT - HCV,MAN SINGH,Sterling Translogistics Private Limited,Lu Latch / Pin,August,Wednesday,9,day,weekday
5,Consent Track,Regular,2020-08-25 15:45:33,Yes,400.0,19 FT OPEN BODY 8 MT,BHARATHIDASAN,Gayathri Transport,Planetary Axle,August,Tuesday,15,day,weekday
9,Vamosys,Regular,2020-08-25 13:39:48,Yes,1199.0,32 FT Multi-Axle 14MT - HCV,GOPALAKRISHNAN M,Arvinth Transport,Mounting Bracket / Round Bar,August,Tuesday,13,day,weekday
10,Nuevastech,Regular,2020-08-25 12:03:57,Yes,1290.0,32 FT Multi-Axle 14MT - HCV,RAMCHANDRA,Pratiksha Freight Carriers,Centering Bolt,August,Tuesday,12,day,weekday

Creating dummy variables for these columns: Days, Hours, Gps Provider and Vehicle Type

In [15]:
weekday_end = pd.get_dummies(tracker_sets["Days"], dtype = int)

In [16]:
days_days = pd.get_dummies(tracker_sets["Hours"], dtype = int)

In [17]:
gps_dummy = pd.get_dummies(tracker_sets["Gps Provider"], dtype = int)

In [18]:
vehicle_dummy = pd.get_dummies(tracker_sets["Vehicle Type"], dtype = int)

In [19]:
tracker_sets = pd.concat([tracker_sets, days_days, weekday_end, gps_dummy, vehicle_dummy], axis=1)

In [20]:
tracker_sets.reset_index()

,index,Gps Provider,Shipment Type,Booking Date,Ontime,Transportation Distance (KM),Vehicle Type,Driver Name,Supplier Name,Material Shipped,...,32 FT Multi-Axle MXL 18MT,32 FT Open Tarus,32 FT Single-Axle 7MT - HCV,40 FT 3XL Trailer 35MT,40 FT Flat Bed Double-Axle 21MT - Trailer,40 FT Flat Bed Multi-Axle 27MT - Trailer,40 FT Flat Bed Single-Axle 20MT - Trailer,Mahindra LCV 1MT,Tata 407 / 14 FT Open 3MT LCV,Tata 407 Open 2MT - Mini-LCV
0,0,Consent Track,Regular,2020-08-26 12:03:46,Yes,1290.0,32 FT Multi-Axle 14MT - HCV,VIRAT NILAPALLE,Oms Logistics Pvt Ltd,Regulator - 12v,...,0,0,0,0,0,0,0,0,0,0
1,4,Consent Track,Regular,2020-08-26 09:55:08,Yes,1900.0,32 FT Single-Axle 7MT - HCV,MAN SINGH,Sterling Translogistics Private Limited,Lu Latch / Pin,...,0,0,1,0,0,0,0,0,0,0
2,5,Consent Track,Regular,2020-08-25 15:45:33,Yes,400.0,19 FT OPEN BODY 8 MT,BHARATHIDASAN,Gayathri Transport,Planetary Axle,...,0,0,0,0,0,0,0,0,0,0
3,9,Vamosys,Regular,2020-08-25 13:39:48,Yes,1199.0,32 FT Multi-Axle 14MT - HCV,GOPALAKRISHNAN M,Arvinth Transport,Mounting Bracket / Round Bar,...,0,0,0,0,0,0,0,0,0,0
4,10,Nuevastech,Regular,2020-08-25 12:03:57,Yes,1290.0,32 FT Multi-Axle 14MT - HCV,RAMCHANDRA,Pratiksha Freight Carriers,Centering Bolt,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2409,3463,Consent Track,Regular,2019-12-30 18:23:49,No,78.5,40 FT 3XL Trailer 35MT,BILAL ALI,Unknown,Solenoid Switch,...,0,0,0,1,0,0,0,0,0,0
2410,3465,Consent Track,Regular,2020-01-07 14:56:40,No,117.0,40 FT 3XL Trailer 35MT,BHARATH HANOKU,United Freight Carriers Private Limited,Solenoid Switch,...,0,0,0,1,0,0,0,0,0,0
2411,3530,Consent Track,Regular,2019-12-26 19:56:20,No,98.1,40 FT Flat Bed Multi-Axle 27MT - Trailer,SHIV LAL MARANDI,Shri Ganesh Traders And Transporter,Plug Modg,...,0,0,0,0,0,1,0,0,0,0
2412,3546,Consent Track,Regular,2019-12-21 18:48:49,No,148.0,40 FT 3XL Trailer 35MT,SUNIL RAJWAR,Shri Ganesh Traders And Transporter,Auto Parts,...,0,0,0,1,0,0,0,0,0,0
2413,3582,Consent Track,Regular,2019-11-30 15:10:27,No,25.0,40 FT 3XL Trailer 35MT,MAHENDRA SINGH,Balaji Freight Carrier,Grs Starter,...,0,0,0,1,0,0,0,0,0,0

normalize the transportation distance variable

In [21]:
mean = tracker_sets["Transportation Distance (KM)"].mean()

In [22]:
std = tracker_sets["Transportation Distance (KM)"].std()

In [23]:
z_scores = (tracker_sets["Transportation Distance (KM)"] - mean)/std

In [24]:
tracker_sets["Transportation_z_scores"] = z_scores

extracting the columns that we now need for the project

In [25]:
new_tracker_sets = tracker_sets.drop(columns = ["Shipment Type", "Gps Provider", "Booking Date", "Vehicle Type", "Driver Name", "Supplier Name", "Material Shipped",
                                           "Month", "Day", "Hour", "Days", "Hours","Transportation Distance (KM)"], axis = 1).reset_index()

removing the "index" column

In [26]:
new_tracker_sets = new_tracker_sets.iloc[:,1:]

In [27]:
new_tracker_sets.head()

,Ontime,morning,day,evening,weekday,weekend,Apace_Transco,Bally Logistics,Beecon,Cargo Carriers,...,32 FT Open Tarus,32 FT Single-Axle 7MT - HCV,40 FT 3XL Trailer 35MT,40 FT Flat Bed Double-Axle 21MT - Trailer,40 FT Flat Bed Multi-Axle 27MT - Trailer,40 FT Flat Bed Single-Axle 20MT - Trailer,Mahindra LCV 1MT,Tata 407 / 14 FT Open 3MT LCV,Tata 407 Open 2MT - Mini-LCV,Transportation_z_scores
0,Yes,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.201747
1,Yes,0,1,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0.902497
2,Yes,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-0.820659
3,Yes,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.097209
4,Yes,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.201747

extracting the target variable

In [28]:
actual_y = new_tracker_sets["Ontime"]

extracting the independent variables

In [29]:
x_variables = new_tracker_sets.drop(columns = ["Ontime"], axis = 1)

spliting the datasets

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x_variables,actual_y, train_size = 0.75, random_state = 1, stratify=actual_y)

creating a model and modifying the maximum iteration to include all the rows

In [31]:
lg_model = LogisticRegression(max_iter = 700)

fitting the datasets

In [32]:
lg_model.fit(x_train, y_train)

LogisticRegression(max_iter=700)

predicting the y variable for the train dataset

In [33]:
predicted_y = lg_model.predict(x_train)

In [34]:
accuracy_score(y_train, predicted_y)

0.7806629834254144

predicting the y variable for the test dataset

In [35]:
pred_y_test = lg_model.predict(x_test)

In [36]:
accuracy_score(y_test, pred_y_test)

0.7798013245033113

Let us predict one Ontime instance a.k.a test out our model

In [75]:
x_example = (0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1.8215132600998545)
x_example = np.asarray(x_example)
x_example = x_example.reshape(1,-1)

In [76]:
lg_model.predict(x_example)

C:\Users\Hp 830 g5 ci5\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array(['No'], dtype=object)

it gave a wrong prediction as the actual value is a yes. what the bloody hell!!!!!!!!!!!

In [41]:
from sklearn.metrics import f1_score

In [55]:
print(f1_score(y_train, predicted_y, pos_label = "No"))
print(f1_score(y_train, predicted_y, pos_label = "Yes"))

0.8687603305785125
0.33277310924369746

In [56]:
print(f1_score(y_test, pred_y_test, pos_label = "No"))
print(f1_score(y_test, pred_y_test, pos_label = "Yes"))

0.8684470820969336
0.32487309644670054

The logistic regression model is obviously not working because it keeps giving wrong results. F1 score is obviosuly poor for the yes labels meaning that there is a false negative error. So we try Random Forest algorithm

In [44]:
random_model = RandomForestClassifier()

In [45]:
random_model.fit(x_train, y_train)

RandomForestClassifier()

In [46]:
ytrain_predict = random_model.predict(x_train)

In [47]:
ytest_predict = random_model.predict(x_test)

In [48]:
accuracy_score(y_train, ytrain_predict)

0.8784530386740331

In [49]:
accuracy_score(y_test, ytest_predict)

0.7897350993377483

In [54]:
print(f1_score(y_train, ytrain_predict, pos_label = "No"))
print(f1_score(y_train, ytrain_predict, pos_label = "Yes"))

0.9206349206349207
0.7405660377358491

In [53]:
print(f1_score(y_test, ytest_predict, pos_label = "No"))
print(f1_score(y_test, ytest_predict, pos_label = "Yes"))

0.8629989212513484
0.5480427046263345

In [77]:
random_model.predict(x_example)

C:\Users\Hp 830 g5 ci5\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array(['No'], dtype=object)